name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: '0.7.22'
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e '.[dev,test]'
      - name: Run unit tests
        run: task test:unit -- --cov-report=xml:coverage.xml
      - name: Run integration tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: task test:integration
    
      - name: Output coverage report to workflow output
        id: coverage_output
        run: |
          echo "coverage_report<<EOF" >> $GITHUB_OUTPUT
          cat coverage.xml >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
